export const MOTION_PRIMITIVE_CATALOG = [
  "animated-background",
  "animated-group",
  "animated-number",
  "border-trail",
  "carousel",
  "cursor",
  "dock",
  "glow-effect",
  "in-view",
  "magnetic",
  "marquee",
  "morphing-dialog",
  "morphing-popover",
  "progressive-blur",
  "scroll-progress",
  "sliding-number",
  "spotlight",
  "text-effect",
  "text-morph",
  "text-roll",
  "text-scramble",
  "tilt",
  "toolbar",
  "transition-panel",
] as const;

export const WATERMELON_COMPONENT_CATALOG = [
  "accordion",
  "alert",
  "announcement",
  "avatar",
  "badge",
  "bento-grid",
  "blog-card",
  "breadcrumb",
  "button",
  "button-group",
  "card",
  "carousel",
  "checkbox",
  "contact-card",
  "dialog",
  "drawer",
  "dropdown-menu",
  "empty-state",
  "feature-card",
  "footer",
  "form",
  "hero",
  "input",
  "logo-cloud",
  "navigation-menu",
  "pagination",
  "popover",
  "progress",
  "radio-group",
  "select",
  "skeleton",
  "slider",
  "stats-card",
  "stepper",
  "switch",
  "tabs",
  "team-card",
  "testimonial",
  "textarea",
  "timeline",
  "toast",
  "toggle",
  "tooltip",
] as const;

export type MotionPrimitiveName = (typeof MOTION_PRIMITIVE_CATALOG)[number];
export type WatermelonComponentName = (typeof WATERMELON_COMPONENT_CATALOG)[number];
