import Link from "next/link";
import { ArrowRight, MoveUpRight, Play, Quote, Sparkles } from "lucide-react";
import { tenantProfile } from "@/src/generated/tenant-profile";
import { cleanRichText, itemImage, itemSummary, itemTitle } from "@/src/lib/content";
import { uiCopy } from "@/src/lib/i18n";
import type { BlockContent, CmsPage, CollectionItem, ContentBlock, MediaAsset, PageResources, SiteSettings } from "@/src/lib/types";
import { cn } from "@/src/lib/utils";
import { ContactForm } from "./contact-form";
import { DecorativeField } from "./decorative-field";
import { GalleryShowcase, type GalleryImage } from "./gallery-showcase";
import { AnimatedGroup, AnimatedGroupItem, BorderTrail, Carousel, GlowEffect, Magnetic, Marquee, Reveal, Spotlight, TextEffect, TiltCard } from "./motion-primitives";
import { WmAccordion, WmBadge, WmBentoGrid, WmCard } from "./watermelon-provider";

const sectionFrame = "mx-auto w-full max-w-[var(--content-width)] px-5 py-[clamp(4.5rem,9vw,8.5rem)]";
const display = "font-[family-name:var(--font-display)] font-black tracking-[-.055em] leading-[.95] text-balance";
const eyebrow = "mb-4 flex items-center gap-2 text-[.68rem] font-black uppercase tracking-[.18em] text-[var(--brand-primary)]";
const primaryButton = "inline-flex min-h-12 items-center justify-center gap-2 rounded-[var(--radius)] border border-[var(--brand-primary)] bg-[var(--brand-primary)] px-5 py-3 text-sm font-black text-white transition hover:-translate-y-0.5 hover:bg-[var(--brand-secondary)]";
const textLink = "inline-flex items-center gap-2 border-b border-current py-1 text-xs font-black uppercase tracking-wider text-[var(--brand-primary)]";

function SectionHead({ block }: { block: BlockContent }) {
  return <div className="mb-[clamp(2.5rem,5vw,4.5rem)] grid items-start gap-6 md:grid-cols-[minmax(220px,.55fr)_minmax(300px,1fr)] md:gap-x-16">{block.eyebrow && <p className={cn(eyebrow, "md:col-span-2")}>{block.eyebrow}</p>}<h2 className={cn(display, "m-0 text-[clamp(2.3rem,4.8vw,4.8rem)]")}>{block.heading}</h2>{block.body && <div className="max-w-2xl text-[var(--muted)]" dangerouslySetInnerHTML={{ __html: cleanRichText(block.body) }}/>}</div>;
}

function Actions({ block }: { block: BlockContent }) {
  if (!block.button_label && !block.secondary_button_label) return null;
  return <div className="mt-8 flex flex-wrap items-center gap-5">{block.button_label && <Magnetic><Link className={primaryButton} href={block.button_url || "#"}>{block.button_label}<ArrowRight size={17}/></Link></Magnetic>}{block.secondary_button_label && <Link className={textLink} href={block.secondary_button_url || "#"}>{block.secondary_button_label}<MoveUpRight size={15}/></Link>}</div>;
}

function HeroCopy({ block, settings, floating = false }: { block: BlockContent; settings: SiteSettings; floating?: boolean }) {
  const copy = uiCopy(settings.default_locale);
  return <Reveal className={cn("relative z-10", floating && "rounded-[2rem] bg-[var(--surface)]/88 p-6 shadow-2xl backdrop-blur md:p-10")}><div className="mb-6 flex items-center justify-between gap-4"><WmBadge><Sparkles size={14}/>{block.eyebrow || settings.organization_type}</WmBadge><span className="font-mono text-[.62rem] text-[var(--muted)]">01 / {settings.default_locale.toUpperCase()}</span></div><TextEffect><h1 className={cn(display, "m-0 max-w-5xl text-[clamp(3.2rem,8vw,8.4rem)]")}>{block.heading || settings.tagline}</h1></TextEffect><div className="mt-6 max-w-2xl text-[clamp(1rem,1.4vw,1.22rem)] text-[var(--muted)]" dangerouslySetInnerHTML={{ __html: cleanRichText(block.body || settings.description) }}/><Actions block={block}/><div className="mt-10 flex flex-wrap gap-x-8 gap-y-2 border-t border-black/10 pt-5 text-xs text-[var(--muted)]"><span>{settings.address || settings.timezone}</span><span>{settings.business_hours || copy.available}</span></div></Reveal>;
}

function Hero({ block, settings }: { block: BlockContent; settings: SiteSettings }) {
  const copy = uiCopy(settings.default_locale);
  const hero = tenantProfile.experience.hero;
  if (hero === "manifesto") return <section className="relative min-h-[calc(100svh-78px)] overflow-hidden bg-[var(--brand-secondary)] px-5 py-20 text-white" id={block.anchor_id || "hero"}><Spotlight className="right-[10%] top-[8%]"/><div className="relative z-10 mx-auto max-w-[var(--content-width)]"><p className="mb-8 font-mono text-xs uppercase tracking-[.25em] text-[var(--brand-accent)]">{block.eyebrow || settings.organization_type}</p><h1 className={cn(display, "m-0 max-w-[13ch] text-[clamp(4rem,12vw,12rem)] uppercase leading-[.78]")}>{block.heading || settings.tagline}</h1><div className="mt-12 grid gap-8 border-t border-white/20 pt-8 md:grid-cols-[1fr_1fr]"><div className="max-w-xl text-lg text-white/65" dangerouslySetInnerHTML={{ __html: cleanRichText(block.body || settings.description) }}/><Actions block={block}/></div></div><DecorativeField compact/><span className="absolute bottom-5 right-5 text-xs uppercase tracking-widest text-white/50">{copy.scroll} ↓</span></section>;
  if (hero === "magazine") return <section className="mx-auto grid min-h-[760px] max-w-[var(--content-width)] grid-cols-12 gap-4 px-5 py-8" id={block.anchor_id || "hero"}><div className="col-span-12 border-b-4 border-[var(--ink)] pb-4 font-mono text-xs uppercase tracking-[.2em] lg:col-span-8">{block.eyebrow || settings.organization_type}</div><div className="relative col-span-12 min-h-[480px] overflow-hidden rounded-[var(--radius)] bg-[var(--brand-primary)]/8 lg:col-span-7">{block.image ? <img className="size-full object-cover" src={block.image.url} alt={block.image.alt_text || block.heading || ""}/> : <DecorativeField/>}<span className="absolute bottom-4 left-4 rounded-full bg-white/85 px-3 py-1 text-xs font-bold backdrop-blur">{block.caption || settings.site_name}</span></div><div className="col-span-12 flex items-end lg:col-span-5"><HeroCopy block={block} settings={settings}/></div></section>;
  if (hero === "immersive") return <section className="relative grid min-h-[calc(100svh-78px)] place-items-end overflow-hidden px-5 py-12" id={block.anchor_id || "hero"}>{block.image && <img className="absolute inset-0 size-full object-cover" src={block.image.url} alt={block.image.alt_text || block.heading || ""}/>}<div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-slate-950/20 to-transparent"/><DecorativeField/><div className="relative mx-auto w-full max-w-[var(--content-width)] text-[var(--ink)]"><HeroCopy block={block} settings={settings} floating/></div></section>;
  return <section className="relative mx-auto grid min-h-[min(760px,calc(100svh-78px))] max-w-[1480px] overflow-hidden lg:grid-cols-[minmax(0,1.02fr)_minmax(420px,.98fr)]" id={block.anchor_id || "hero"}><div className="flex items-center px-[clamp(1.5rem,6vw,6.5rem)] py-[clamp(4rem,8vw,8rem)]"><HeroCopy block={block} settings={settings}/></div><div className="relative min-h-[520px] overflow-hidden bg-[var(--brand-primary)]/7"><DecorativeField/><GlowEffect className="right-0 top-0"/>{block.image && <div className="absolute bottom-[clamp(2.5rem,7vw,6rem)] right-[clamp(1.5rem,5vw,5rem)] aspect-[4/5] w-[min(68%,430px)] rotate-[2.5deg] overflow-hidden rounded-[calc(var(--radius)*1.4)] border-[7px] border-white/80 shadow-2xl"><img className="size-full object-cover" src={block.image.url} alt={block.image.alt_text || block.image.title || ""}/><span className="absolute bottom-0 left-0 bg-[var(--brand-secondary)] px-4 py-2 text-[.62rem] uppercase tracking-widest text-white">{block.caption || block.image.category}</span></div>}<span className="absolute bottom-4 right-5 font-mono text-[.6rem] tracking-wider text-[var(--muted)]">{settings.map?.latitude || "00.000"} / {settings.map?.longitude || "000.000"}</span></div></section>;
}

function Stats({ block }: { block: BlockContent }) {
  const pattern = String(tenantProfile.designSystem.uspPattern || "metric-ribbon");
  return <section className={cn("bg-[var(--brand-secondary)] text-white", pattern === "bento-proof" && "bg-[var(--surface)] text-[var(--ink)]", pattern === "service-timeline" && "bg-[var(--brand-primary)]")}><div className={sectionFrame}><SectionHead block={block}/><AnimatedGroup className={cn("grid border-t border-white/20 md:grid-cols-3", pattern === "bento-proof" && "gap-4 border-0 md:grid-cols-2 xl:grid-cols-4")}>{block.items?.map((item) => <AnimatedGroupItem key={item.id}><div className={cn("grid min-h-56 content-end border-b border-white/20 p-6 md:border-b-0 md:border-r", pattern === "bento-proof" && "rounded-[var(--radius)] border border-black/10 bg-[var(--brand-primary)]/8", pattern === "icon-led-grid" && "min-h-44 place-items-start content-start")}><strong className="font-[family-name:var(--font-display)] text-[clamp(3.5rem,7vw,7rem)] font-black leading-[.9] tracking-[-.07em] text-[var(--brand-accent)]">{item.value}</strong><span className="mt-4 text-xs font-black uppercase tracking-wider">{item.label}</span><small className={cn(pattern === "bento-proof" ? "text-[var(--muted)]" : "text-white/55")}>{item.caption}</small></div></AnimatedGroupItem>)}</AnimatedGroup></div></section>;
}

function Callout({ block }: { block: BlockContent }) {
  const pattern = String(tenantProfile.designSystem.ctaPattern || "contrast-panel");
  return <section className={sectionFrame}><Reveal><div className={cn("relative flex min-h-[480px] items-center overflow-hidden rounded-[calc(var(--radius)*1.5)] bg-[var(--brand-primary)]/10 p-[clamp(2rem,7vw,6rem)]", pattern === "full-bleed-band" && "rounded-none bg-[var(--brand-secondary)] text-white", pattern === "magnetic-pill" && "rounded-full", pattern === "split-invitation" && "min-h-[360px] lg:ml-[12vw]")}><BorderTrail/><DecorativeField compact/><div className="relative z-10 max-w-3xl"><p className={eyebrow}>{block.eyebrow || "Make it real"}</p><h2 className={cn(display, "text-[clamp(2.5rem,6vw,6rem)]")}>{block.heading}</h2><div className="mt-5 text-[var(--muted)]" dangerouslySetInnerHTML={{ __html: cleanRichText(block.body) }}/><Actions block={block}/></div></div></Reveal></section>;
}

function RichText({ block }: { block: BlockContent }) { return <section className={sectionFrame} id={block.anchor_id || undefined}><SectionHead block={block}/><div className="prose prose-lg max-w-4xl text-[var(--muted)] prose-headings:font-[family-name:var(--font-display)] prose-headings:text-[var(--ink)]" dangerouslySetInnerHTML={{ __html: cleanRichText(block.body) }}/><Actions block={block}/></section>; }

function ImageText({ block }: { block: BlockContent }) {
  const reverse = block.layout === "reverse" || tenantProfile.experience.sectionRhythm === "alternating";
  return <section className={cn(sectionFrame, "grid items-center gap-[clamp(2rem,7vw,7rem)] lg:grid-cols-[minmax(0,1fr)_minmax(320px,.8fr)]")} id={block.anchor_id || undefined}><Reveal className={cn("relative min-h-[520px] overflow-hidden rounded-[calc(var(--radius)*1.4)] bg-[var(--brand-primary)]/8", reverse && "lg:order-2")}>{block.image ? <img className="absolute inset-0 size-full object-cover" src={block.image.url} alt={block.image.alt_text || block.heading || ""}/> : <DecorativeField compact/>}</Reveal><Reveal><p className={eyebrow}>{block.eyebrow}</p><h2 className={cn(display, "text-[clamp(2.4rem,5vw,5rem)]")}>{block.heading}</h2><div className="mt-6 text-[var(--muted)]" dangerouslySetInnerHTML={{ __html: cleanRichText(block.body) }}/><Actions block={block}/></Reveal></section>;
}

function VideoSection({ block, locale }: { block: BlockContent; locale: string }) {
  const copy = uiCopy(locale);
  return <section className={sectionFrame}><SectionHead block={block}/><div className="relative aspect-video overflow-hidden rounded-[calc(var(--radius)*1.4)] bg-[var(--brand-secondary)]">{block.video_url ? <iframe className="size-full border-0" src={block.video_url} title={block.heading || "Video"} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/> : block.image ? <><img className="size-full object-cover" src={block.image.url} alt={block.image.alt_text || block.heading || ""}/><span className="absolute inset-0 m-auto grid size-20 place-items-center rounded-full bg-[var(--brand-accent)] text-[var(--brand-secondary)]"><Play fill="currentColor"/></span></> : <div className="grid size-full place-items-center text-white/70">{copy.noVideo}</div>}</div></section>;
}

function ItemGrid({ block, className = "" }: { block: BlockContent; className?: string }) {
  const items = block.items?.slice(0, block.item_limit || 12) || [];
  return <section className={cn(sectionFrame, className)} id={block.anchor_id || undefined}><SectionHead block={block}/><WmBentoGrid>{items.map((item, index) => <Reveal className={cn(index === 0 && items.length > 3 && "md:col-span-2 xl:col-span-6", "xl:col-span-4")} key={item.id} delay={Math.min(index * .06, .3)}><TiltCard className="h-full"><WmCard className="relative h-full min-h-72 overflow-hidden"><span className="absolute right-5 top-5 font-mono text-xs text-[var(--brand-primary)]">{item.icon || String(index + 1).padStart(2, "0")}</span>{item.image && <img className="mb-6 aspect-[16/9] w-full rounded-xl object-cover" src={item.image.url} alt={item.image.alt_text || item.title || ""}/>}<h3 className="mt-10 font-[family-name:var(--font-display)] text-2xl font-black tracking-tight">{item.title || item.label}</h3>{item.value && <strong className="block font-[family-name:var(--font-display)] text-5xl text-[var(--brand-primary)]">{item.value}</strong>}<div className="mt-3 text-[var(--muted)]" dangerouslySetInnerHTML={{ __html: cleanRichText(item.body) }}/>{item.url && <Link className={cn(textLink, "mt-5")} href={item.url}>{item.label || "Explore"}<ArrowRight size={15}/></Link>}</WmCard></TiltCard></Reveal>)}</WmBentoGrid><Actions block={block}/></section>;
}

function Testimonials({ block }: { block: BlockContent }) { const pattern = String(tenantProfile.designSystem.testimonialPattern || "quote-cards"); return <section className={sectionFrame}><SectionHead block={block}/><Carousel>{block.items?.map((item) => <blockquote className={cn("m-0 rounded-[calc(var(--radius)*1.2)] border border-black/10 bg-[var(--brand-primary)]/5 p-[clamp(1.7rem,4vw,3.2rem)]", pattern === "single-quote" && "border-l-8 border-l-[var(--brand-accent)] rounded-none bg-transparent", pattern === "stacked-notes" && "rotate-[-1deg] shadow-xl", pattern === "editorial-pullquote" && "rounded-none border-x-0 border-t-4 border-[var(--ink)]")} key={item.id}><Quote className="text-[var(--brand-primary)]"/><div className="my-6 font-[family-name:var(--font-display)] text-[clamp(1.3rem,2vw,2rem)] font-bold tracking-tight" dangerouslySetInnerHTML={{ __html: cleanRichText(item.body) }}/><footer className="flex items-center gap-3">{item.image && <img className="size-12 rounded-full object-cover" src={item.image.url} alt=""/>}<span className="grid"><strong>{item.title}</strong><small className="text-[var(--muted)]">{item.caption || item.label}</small></span></footer></blockquote>)}</Carousel></section>; }

function LogoCloud({ block }: { block: BlockContent }) { const items = block.items || []; return <section className={sectionFrame}><p className={eyebrow}>{block.eyebrow}</p><h2 className={cn(display, "mb-12 max-w-4xl text-[clamp(2.4rem,5vw,5rem)]")}>{block.heading}</h2><Marquee><div className="flex min-w-max">{items.map((item) => <div className="grid min-h-36 min-w-56 place-items-center border border-black/10 p-6 text-center" key={item.id}>{item.image ? <img className="max-h-16 max-w-36 object-contain grayscale" src={item.image.url} alt={item.title || item.label || ""}/> : <strong>{item.title || item.label}</strong>}<small className="text-[var(--muted)]">{item.caption}</small></div>)}</div></Marquee></section>; }

function CollectionCards({ block, items, path, locale }: { block: BlockContent; items: CollectionItem[]; path: string; locale: string }) {
  const copy = uiCopy(locale);
  return <section className={sectionFrame}><SectionHead block={block}/><div className="grid gap-5 md:grid-cols-2">{items.slice(0, block.item_limit || 6).map((item, index) => { const image = itemImage(item); return <Reveal key={String(item.slug || index)} delay={index * .06}><TiltCard className="h-full"><WmCard className="h-full overflow-hidden p-0"><Link className="grid h-full" href={`/${path}/${item.slug}`}><div className="relative aspect-[16/10] overflow-hidden bg-[var(--brand-primary)]/10">{image ? <img className="size-full object-cover transition duration-700 hover:scale-105" src={image.url} alt={image.alt_text || itemTitle(item)}/> : <div className="grid size-full place-items-center font-mono text-5xl text-[var(--brand-primary)]">{String(index + 1).padStart(2, "0")}</div>}<span className="absolute left-4 top-4 rounded-full bg-[var(--surface)]/88 px-3 py-1 text-[.62rem] font-black uppercase tracking-wider backdrop-blur">{String(item.extra?.category || item.extra?.industry || path)}</span></div><div className="p-7"><h2 className="font-[family-name:var(--font-display)] text-3xl font-black tracking-tight">{itemTitle(item)}</h2><p className="mt-3 text-[var(--muted)]">{itemSummary(item)}</p><span className={cn(textLink, "mt-6")}>{copy.viewDetail}<ArrowRight size={15}/></span></div></Link></WmCard></TiltCard></Reveal>; })}</div><div className="mt-10 flex justify-center"><Link className={primaryButton} href={`/${path}`}>{copy.viewAll} {path}<ArrowRight size={16}/></Link></div></section>;
}

function FaqSection({ block, items }: { block: BlockContent; items: CollectionItem[] }) { const rows: CollectionItem[] = items.length ? items : (block.items || []).map((item) => ({ slug: item.id, title: item.title || item.label || "", body: item.body || "" })); return <section className={sectionFrame}><SectionHead block={block}/><WmAccordion rows={rows.slice(0, block.item_limit || 10).map((item, index) => ({ id: String(item.slug || index), title: String(item.extra?.question || itemTitle(item)), body: cleanRichText(String(item.extra?.answer || item.body || "")) }))}/></section>; }

function GallerySection({ block, galleries, locale }: { block: BlockContent; galleries: CollectionItem[]; locale: string }) { const copy = uiCopy(locale); const fromGalleries = galleries.flatMap((gallery) => Array.isArray(gallery.items) ? gallery.items as Array<Record<string, unknown>> : []).map((media, index) => ({ id: String(media.id || index), url: String(media.url || ""), title: String(media.title || media.caption || ""), caption: String(media.caption || ""), alt_text: String(media.alt_text || media.title || ""), category: String(media.category || "Gallery") })); const fromBlock = (block.items || []).filter((item) => item.image).map((item) => ({ ...(item.image as MediaAsset), caption: item.caption || item.title })); const images = (fromGalleries.length ? fromGalleries : fromBlock).filter((item) => item.url) as GalleryImage[]; return <section className={sectionFrame}><SectionHead block={block}/><GalleryShowcase images={images} locale={locale}/><div className="mt-10 flex justify-center"><Link className={primaryButton} href="/galleries">{copy.openGallery}<ArrowRight size={16}/></Link></div></section>; }
function ContactSection({ block, resources, locale }: { block: BlockContent; resources: PageResources; locale: string }) { if (!resources.form) return <ItemGrid block={block}/>; return <section className={sectionFrame}><SectionHead block={block}/><ContactForm schema={resources.form} eyebrow={block.eyebrow || "Start a conversation"} locale={locale}/></section>; }

export function CmsRenderer({ page, settings, resources = {} }: { page: CmsPage; settings: SiteSettings; resources?: PageResources }) {
  const locale = settings.default_locale;
  if (!page.blocks?.length) return <section className={sectionFrame}><p className={eyebrow}>{page.page_type}</p><h1 className={cn(display, "text-[clamp(3rem,8vw,8rem)]")}>{page.title}</h1><p className="mt-6 max-w-2xl text-[var(--muted)]">{page.excerpt}</p></section>;
  return <>{page.blocks.map((block: ContentBlock, index) => { const key = block.content.id || `${block.type}-${index}`; if (block.type === "hero") return <Hero key={key} block={block.content} settings={settings}/>; if (block.type === "stats") return <Stats key={key} block={block.content}/>; if (block.type === "cta") return <Callout key={key} block={block.content}/>; if (block.type === "rich_text") return <RichText key={key} block={block.content}/>; if (block.type === "image_text") return <ImageText key={key} block={block.content}/>; if (block.type === "video") return <VideoSection key={key} block={block.content} locale={locale}/>; if (block.type === "feature_grid") return <ItemGrid key={key} block={block.content}/>; if (block.type === "testimonial") return <Testimonials key={key} block={block.content}/>; if (block.type === "logo_cloud") return <LogoCloud key={key} block={block.content}/>; if (block.type === "faq_list") return <FaqSection key={key} block={block.content} items={resources.faq || []}/>; if (block.type === "blog_list") return <CollectionCards key={key} block={block.content} items={resources.blog || []} path="blog" locale={locale}/>; if (block.type === "product_list") return <CollectionCards key={key} block={block.content} items={resources.products || []} path="products" locale={locale}/>; if (block.type === "project_list") return <CollectionCards key={key} block={block.content} items={resources.projects || []} path="projects" locale={locale}/>; if (block.type === "portfolio_list") return <CollectionCards key={key} block={block.content} items={resources.portfolio || []} path="portfolio" locale={locale}/>; if (block.type === "career_list") return <CollectionCards key={key} block={block.content} items={resources.careers || []} path="careers" locale={locale}/>; if (block.type === "legal_list") return <CollectionCards key={key} block={block.content} items={resources.legal || []} path="legal" locale={locale}/>; if (block.type === "gallery") return <GallerySection key={key} block={block.content} galleries={resources.galleries || []} locale={locale}/>; if (block.type === "contact_form") return <ContactSection key={key} block={block.content} resources={resources} locale={locale}/>; return <ItemGrid key={key} block={block.content}/>; })}</>;
}
