import Link from "next/link";
import { ArrowLeft, ArrowRight, CalendarDays, MapPin } from "lucide-react";
import { cleanRichText, collectionLabel, itemBody, itemImage, itemSummary, itemTitle } from "@/src/lib/content";
import { uiCopy } from "@/src/lib/i18n";
import type { CollectionItem } from "@/src/lib/types";
import { formatDate } from "@/src/lib/utils";
import { GalleryShowcase } from "./gallery-showcase";
import { Reveal, TiltCard } from "./motion-primitives";
import { WmAccordion, WmCard } from "./watermelon-provider";

const frame = "mx-auto max-w-[var(--content-width)] px-5 py-[clamp(4.5rem,9vw,8.5rem)]";
const display = "font-[family-name:var(--font-display)] font-black tracking-[-.055em] leading-[.95]";

function destination(key: string, item: CollectionItem) { const slug = String(item.slug || item.key || ""); return slug ? `/${key}/${slug}` : `/${key}`; }

export function CollectionView({ collectionKey, items, locale }: { collectionKey: string; items: CollectionItem[]; locale?: string }) {
  const copy = uiCopy(locale);
  if (collectionKey === "faq") return <section className={frame}><CollectionIntro collectionKey={collectionKey} count={items.length} locale={locale}/><WmAccordion rows={items.map((item, index) => ({ id: String(item.slug || index), title: String(item.extra?.question || itemTitle(item)), body: cleanRichText(String(item.extra?.answer || itemBody(item))) }))}/></section>;
  if (collectionKey === "galleries") { const media = items.flatMap((gallery) => Array.isArray(gallery.items) ? gallery.items as Array<Record<string, unknown>> : []).map((asset, index) => ({ id: String(asset.id || index), url: String(asset.url || ""), alt_text: String(asset.alt_text || asset.title || ""), title: String(asset.title || ""), description: String(asset.description || ""), category: String(asset.category || "Gallery"), caption: String(asset.caption || asset.title || "") })); return <section className={frame}><CollectionIntro collectionKey={collectionKey} count={media.length} locale={locale}/><GalleryShowcase images={media} locale={locale}/></section>; }
  return <section className={frame}><CollectionIntro collectionKey={collectionKey} count={items.length} locale={locale}/><div className="grid gap-5 md:grid-cols-2">{items.map((item, index) => { const image = itemImage(item); const extra = item.extra || {}; return <Reveal key={String(item.slug || item.key || index)} delay={Math.min(index * .07, .28)}><TiltCard className="h-full"><WmCard className="h-full overflow-hidden p-0"><Link className="grid h-full" href={destination(collectionKey, item)} aria-label={itemTitle(item)}>{image ? <div className="relative aspect-[16/10] overflow-hidden bg-[var(--brand-primary)]/10"><img className="size-full object-cover transition duration-700 hover:scale-105" src={image.url} alt={image.alt_text || itemTitle(item)}/><span className="absolute left-4 top-4 rounded-full bg-[var(--surface)]/88 px-3 py-1 text-[.62rem] font-black uppercase tracking-wider backdrop-blur">{String(extra.category || extra.industry || extra.product_type || collectionLabel(collectionKey))}</span></div> : <div className="grid aspect-[16/10] place-items-center bg-[var(--brand-primary)]/10 font-mono text-5xl text-[var(--brand-primary)]">{String(index + 1).padStart(2, "0")}</div>}<div className="p-7"><p className="flex flex-wrap gap-3 text-xs text-[var(--muted)]">{item.published_at && <span className="inline-flex items-center gap-1"><CalendarDays size={14}/>{formatDate(item.published_at)}</span>}{Boolean(extra.location) && <span className="inline-flex items-center gap-1"><MapPin size={14}/>{String(extra.location)}</span>}</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-3xl font-black tracking-tight">{itemTitle(item)}</h2><p className="mt-3 text-[var(--muted)]">{itemSummary(item)}</p><span className="mt-6 inline-flex items-center gap-2 border-b border-current py-1 text-xs font-black uppercase tracking-wider text-[var(--brand-primary)]">{copy.viewDetail}<ArrowRight size={15}/></span></div></Link></WmCard></TiltCard></Reveal>; })}</div></section>;
}

function CollectionIntro({ collectionKey, count, locale }: { collectionKey: string; count: number; locale?: string }) { const copy = uiCopy(locale); return <div className="mb-16 grid items-end gap-5 md:grid-cols-[1fr_.65fr]"><p className="text-[.68rem] font-black uppercase tracking-[.18em] text-[var(--brand-primary)] md:col-span-2">{copy.explore} / {String(count).padStart(2, "0")}</p><h1 className={`${display} m-0 text-[clamp(3.2rem,8vw,8rem)]`}>{collectionLabel(collectionKey)}</h1><p className="max-w-md text-[var(--muted)]">{copy.latestContent}</p></div>; }

export function CollectionDetail({ collectionKey, item, locale }: { collectionKey: string; item: CollectionItem; locale?: string }) {
  const copy = uiCopy(locale); const image = itemImage(item); const extra = item.extra || {};
  return <article className="mx-auto max-w-[1120px] px-5 py-[clamp(4.5rem,9vw,8.5rem)]"><Link className="mb-14 inline-flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[var(--brand-primary)]" href={`/${collectionKey}`}><ArrowLeft size={16}/>{copy.backTo} {collectionLabel(collectionKey)}</Link><header className="mb-14 max-w-4xl"><p className="mb-4 text-[.68rem] font-black uppercase tracking-[.18em] text-[var(--brand-primary)]">{String(extra.category || extra.industry || collectionLabel(collectionKey))}</p><h1 className={`${display} m-0 text-[clamp(3rem,7vw,6.5rem)]`}>{itemTitle(item)}</h1><p className="mt-6 max-w-3xl text-lg text-[var(--muted)]">{itemSummary(item)}</p></header>{image && <figure className="mb-14"><img className="max-h-[680px] w-full rounded-[calc(var(--radius)*1.2)] object-cover" src={image.url} alt={image.alt_text || itemTitle(item)}/><figcaption className="mt-2 text-xs text-[var(--muted)]">{image.description}</figcaption></figure>}<div className="grid gap-12 lg:grid-cols-[1fr_320px]"><div className="prose prose-lg max-w-none text-[var(--ink)] prose-a:text-[var(--brand-primary)]" dangerouslySetInnerHTML={{ __html: cleanRichText(itemBody(item)) }}/><aside className="self-start border-t-2 border-[var(--brand-primary)]">{Object.entries(extra).filter(([, value]) => typeof value === "string" || typeof value === "number" || Array.isArray(value)).slice(0, 8).map(([key, value]) => <div className="grid gap-1 border-b border-black/10 py-4" key={key}><span className="text-[.62rem] uppercase tracking-wider text-[var(--muted)]">{key.replaceAll("_", " ")}</span><strong className="text-sm">{Array.isArray(value) ? value.join(" · ") : String(value)}</strong></div>)}</aside></div></article>;
}
