import { Clock3, Mail, MapPin, Navigation, Phone } from "lucide-react";
import { uiCopy } from "@/src/lib/i18n";
import type { SiteLocation } from "@/src/lib/types";
import { cn } from "@/src/lib/utils";
import { WmCard } from "./watermelon-provider";

export function LocationSection({ locations, locale }: { locations: SiteLocation[]; locale?: string }) {
  if (!locations.length) return null;
  const copy = uiCopy(locale); const primary = locations.find((item) => item.is_primary) || locations[0]; const lat = primary.coordinates.latitude; const lng = primary.coordinates.longitude; const delta = .02;
  const mapUrl = `https://www.openstreetmap.org/export/embed.html?bbox=${Number(lng)-delta}%2C${Number(lat)-delta}%2C${Number(lng)+delta}%2C${Number(lat)+delta}&layer=mapnik&marker=${lat}%2C${lng}`;
  return <section className="mx-auto max-w-[var(--content-width)] px-5 py-[clamp(4.5rem,9vw,8.5rem)]"><div className="mb-14 grid items-start gap-6 md:grid-cols-[.55fr_1fr]"><p className="text-[.68rem] font-black uppercase tracking-[.18em] text-[var(--brand-primary)] md:col-span-2">{copy.where}</p><h2 className="font-[family-name:var(--font-display)] text-[clamp(2.3rem,4.8vw,4.8rem)] font-black leading-[.95] tracking-[-.055em]">{copy.visitTitle}</h2><p className="max-w-2xl text-[var(--muted)]">{copy.visitDescription}</p></div><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="relative min-h-[620px] overflow-hidden rounded-[calc(var(--radius)*1.2)] bg-slate-200"><iframe className="size-full min-h-[620px] border-0" title={`Map ${primary.name}`} src={mapUrl} loading="lazy"/><a className="absolute bottom-4 right-4 inline-flex items-center gap-2 rounded-xl bg-[var(--brand-secondary)] px-4 py-3 text-sm font-black text-white" href={`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=${primary.coordinates.zoom}/${lat}/${lng}`} target="_blank" rel="noopener noreferrer"><Navigation size={16}/>{copy.directions}</a></div><div className="grid gap-4">{locations.map((location) => <WmCard className={cn("p-6", location.is_primary && "bg-[var(--brand-primary)]/8")} key={location.key}><span className="text-[.68rem] font-black uppercase tracking-wider text-[var(--brand-primary)]">{location.type}{location.is_primary ? ` · ${copy.primaryLocation}` : ""}</span><h3 className="my-3 font-[family-name:var(--font-display)] text-3xl font-black">{location.name}</h3><div className="grid gap-3 text-sm text-[var(--muted)]"><p className="flex gap-2"><MapPin className="shrink-0" size={16}/>{location.address}</p>{location.phone && <a className="flex gap-2" href={`tel:${location.phone}`}><Phone size={16}/>{location.phone}</a>}{location.email && <a className="flex gap-2" href={`mailto:${location.email}`}><Mail size={16}/>{location.email}</a>}{location.business_hours && <p className="flex gap-2"><Clock3 size={16}/>{location.business_hours}</p>}</div></WmCard>)}</div></div></section>;
}
