import Link from "next/link";
import { ArrowUpRight, Clock3, Mail, MapPin, Phone } from "lucide-react";
import { tenantProfile } from "@/src/generated/tenant-profile";
import { uiCopy } from "@/src/lib/i18n";
import type { BrandConfig, FooterConfig, SiteLocation, SiteSettings } from "@/src/lib/types";
import { cn, safeExternalUrl } from "@/src/lib/utils";
import { TextEffect } from "./motion-primitives";
import { NewsletterForm } from "./newsletter-form";
import { BrandMark } from "./site-header";

export function SiteFooter({ settings, branding, footer, locations = [], locale }: { settings: SiteSettings; branding?: BrandConfig; footer: FooterConfig; locations?: SiteLocation[]; locale?: string }) {
  const primary = locations.find((item) => item.is_primary) || locations[0];
  const copy = uiCopy(locale);
  const variant = tenantProfile.experience.footer;
  const pattern = String(tenantProfile.designSystem.footerPattern || variant);
  return <footer className={cn("relative overflow-hidden bg-[var(--footer-bg)] px-[max(1.25rem,calc((100vw-var(--content-width))/2+1.5rem))] pb-6 pt-16 text-[var(--footer-ink)]", variant === "editorial" && "border-t-[12px] border-[var(--brand-accent)]", variant === "contact-led" && "pt-24", pattern === "map-first" && "pt-28", pattern === "compact-proof" && "pt-10", pattern === "newsletter-studio" && "bg-[var(--brand-secondary)]")}>
    <div className={cn("grid items-end gap-6 border-b border-white/15 pb-12 md:grid-cols-[1fr_auto]", variant === "compact" && "pb-7")}><div><p className="mb-4 text-xs font-black uppercase tracking-[.18em] text-[var(--brand-accent)]">{copy.nextChapter}</p><TextEffect><h2 className={cn("m-0 max-w-5xl font-[family-name:var(--font-display)] text-[clamp(2.8rem,7vw,7rem)] font-black leading-[.9] tracking-[-.065em]", variant === "editorial" && "uppercase italic")}>{footer.heading}</h2></TextEffect></div><Link className="grid size-20 place-items-center rounded-full border border-white/30 transition hover:rotate-45 hover:bg-[var(--brand-accent)] hover:text-[var(--footer-bg)]" href={settings.contact_cta?.url || "/contact"} aria-label={copy.contact}><ArrowUpRight size={32}/></Link></div>
    <div className={cn("grid gap-10 py-12 sm:grid-cols-2 lg:grid-cols-4", variant === "mega" && "xl:grid-cols-6", variant === "compact" && "lg:grid-cols-3")}><div className={cn("sm:col-span-2", variant === "mega" && "xl:col-span-2")}><BrandMark settings={settings} branding={branding} inverted/><p className="mt-6 max-w-md text-sm leading-7 text-white/65">{footer.description}</p><div className="mt-6 grid gap-3 text-sm text-white/70">{settings.contact_email && <a className="flex gap-2" href={`mailto:${settings.contact_email}`}><Mail size={16}/>{settings.contact_email}</a>}{settings.contact_phone && <a className="flex gap-2" href={`tel:${settings.contact_phone}`}><Phone size={16}/>{settings.contact_phone}</a>}{settings.address && <span className="flex gap-2"><MapPin className="shrink-0" size={16}/>{settings.address}</span>}{settings.business_hours && <span className="flex gap-2"><Clock3 size={16}/>{settings.business_hours}</span>}</div>{footer.social_links && footer.visibility?.social_links !== false && <div className="mt-7 flex flex-wrap gap-4">{footer.social_links.map((social) => <a className="inline-flex items-center gap-1 text-xs font-black uppercase tracking-wider" key={social.platform} href={safeExternalUrl(social.url)} target="_blank" rel="noopener noreferrer">{social.label || social.platform}<ArrowUpRight size={13}/></a>)}</div>}</div>{footer.columns?.map((column) => <div key={column.id}><h3 className="mb-4 text-xs font-black uppercase tracking-[.14em] text-white/45">{column.title}</h3><div className="grid gap-3">{column.links.map((link) => <Link className="text-sm font-bold text-white/80 hover:text-white" href={safeExternalUrl(link.url)} key={`${column.id}-${link.label}`} target={link.target}>{link.label}</Link>)}</div></div>)}{footer.newsletter?.enabled && footer.newsletter.form_key && <div className="sm:col-span-2"><p className="text-xs font-black uppercase tracking-[.14em] text-[var(--brand-accent)]">{copy.newsletter}</p><h3 className="mt-3 font-[family-name:var(--font-display)] text-2xl font-black">{footer.newsletter.heading}</h3><p className="text-sm text-white/60">{footer.newsletter.description}</p><NewsletterForm formKey={footer.newsletter.form_key} locale={locale}/></div>}</div>
    {primary && footer.visibility?.map_link && <a className="flex items-center gap-2 border-y border-white/15 py-4 text-sm font-bold" href={`https://www.openstreetmap.org/?mlat=${primary.coordinates.latitude}&mlon=${primary.coordinates.longitude}`} target="_blank" rel="noopener noreferrer"><MapPin size={16}/>{primary.name} · {copy.openMap}<ArrowUpRight size={14}/></a>}
    <div className="flex flex-col justify-between gap-2 pt-6 text-xs text-white/45 sm:flex-row"><span>{footer.copyright}</span><span>{settings.legal_name}{settings.registration_number ? ` · ${settings.registration_number}` : ""}</span></div>
  </footer>;
}
